name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always 

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies 
      run: sudo apt install libudev-dev xorg openbox x11vnc && sudo systemctl daemon-reload && sudo systemctl start x11vnc
    - name: set display
      run: x11vnc -display :1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo
      run: cargo run 
